### PR TITLE
Work fix6

### PR DESCRIPTION
**Pull request by namjaejeon**

### CODE REVIEW

**Review by jaysim — COMMENTED** [review]
ntfsck does not check $BITMAP on btree lookup yet.
is it right to remove this function at this time?

**Review by jaysim — COMMENTED** [review]
I don't have enough automake skills to comment/review this patch.
But I understood that this patch remove unnecessary files and build with static linking, right?

**Comment by namjaejeon** [comment]
> is it right to remove this function at this time?

bitmap lookup also doesn't fix it yet. just lookup files... and no plan to fix it on bitmap lookup. Because two all files lookup iteration cause performance drop.

**Comment by namjaejeon** [comment]
> But I understood that this patch remove unnecessary files and build with static linking, right?

Ah, yes, remove unused util and library. So this patch just remove libfuse and ntfs-3g mount helpers in configure. we probably can build ntfsprogs with static linking regardless of this patch.

**Comment by namjaejeon** [comment]
As you know, We will change private tree to public next month. So before that, I would like to make ntfsprogs's one set that not included ntfs3g leftover.

**Comment by namjaejeon** [comment]
Applied.

**Pull request closed without merging**
