### PR TITLE
work-fix11

### PR DESCRIPTION
**Pull request by namjaejeon**

### CODE REVIEW

**Comment by namjaejeon** [comment]
@jaysim Could you please run address sanitizer to know whether memleak is fixed or not in system files check ?

**Comment by jaysim** [comment]
Address sanitizer execution result is as below.
If you build ntfsprogs with address sanitizer, execute configure with option : 
CFLAGS="-fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-fsanitize=address -ldl" ./configure

Direct leak of 544 byte(s) in 4 object(s) allocated from:                                                                                                                                                                           
    #0 0x7f48fef39a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153                                                                                                                            
    #1 0x7f48fedba19e in ntfs_calloc /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/misc.c:47                                                                                                                          
    #2 0x7f48fed9babc in __ntfs_inode_allocate /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/inode.c:95
    #3 0x7f48fed9bcf5 in ntfs_inode_real_open /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/inode.c:171
    #4 0x7f48fed9de62 in ntfs_inode_open /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/inode.c:486
    #5 0x55b5342df785 in ntfsck_check_system_files /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/src/ntfsck.c:2512
    #6 0x55b5342e005f in main /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/src/ntfsck.c:2657
    #7 0x7f48feb45082 in __libc_start_main ../csu/libc-start.c:308

Indirect leak of 4096 byte(s) in 4 object(s) allocated from:
    #0 0x7f48fef39808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f48fedba207 in ntfs_malloc /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/misc.c:57
    #2 0x7f48fedb1285 in ntfs_file_record_read /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/mft.c:436
    #3 0x7f48fed9bd21 in ntfs_inode_real_open /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/inode.c:174
    #4 0x7f48fed9de62 in ntfs_inode_open /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/libntfs-3g/inode.c:486
    #5 0x55b5342df785 in ntfsck_check_system_files /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/src/ntfsck.c:2512
    #6 0x55b5342e005f in main /home/pinocc/Projects/filesystems/ntfs/ntfsprogs/src/ntfsck.c:2657
    #7 0x7f48feb45082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 4640 byte(s) leaked in 8 allocation(s).

**Comment by namjaejeon** [comment]
@jaysim Thanks, FIXED.

**Comment by namjaejeon** [comment]
Applied.

**Pull request closed without merging**
